### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by vixducis** [victor/whereami#1]
I've downloaded the mach-O universal binary, placed it in /usr/local/bin, and made it executable. Now when I type whereami in the terminal, it asks me to make use of the location services. But when I give permission, the terminal 'freezes up' and does nothing.

**Comment by victor** [comment]
What kind of system do you have?

Also, you need to have enabled wifi networking, even if you're not associated with any network. And you need internet connectivity as well (even if you connect via the ethernet adapter or a modem, not necessarily via wifi). Do you have this enabled?

**Comment by vixducis** [comment]
I am working on a mid 2009 macbook pro, have an active internet connection via wifi, so there shouldn't be any problems. I'm running the latest snow leopard release.

**Comment by victor** [comment]
Perhaps it's taking too long to acquire a location fix. I will add a timeout to avoid it waiting indefinitely. 
Do other CoreLocation based apps work for you? (for example, check in the timezone preferences)

**Comment by vixducis** [comment]
You're right, it's not your application that's faulty, its CoreLocation, in the Timezone prefpanel, i get "Can't determine current location". Probably because there aren't any wifi networks in the neighboorheid known to apple.

**Comment by victor** [comment]
Thanks for reporting this issue. I will add code to handle this specific case.
Out of curiosity, where are you located? Even in the small town where I live, I can get a location - even if it's off by a couple of km.

**Comment by vixducis** [comment]
http://maps.google.com/maps?q=51.255711,4.786992&num=1&t=h&sll=51.253642,4.785428&sspn=0.011294,0.01929&ie=UTF8&ll=51.255684,4.786971&spn=0.011294,0.01929&z=16
a very small town in belgium

Opera's geolocation gives me a position that's only like a couple of 100m avay.

**Comment by victor** [comment]
Opera is probably using Skyhook API directly. If you check the Clarke app (http://github.com/tomtaylor/Clarke), it uses Skyhook API where CoreLocation is not available (that is, in Leopard). However, using it in an open-source app is so involved (you need to get an API key and so on...) that I chose not to support it and require CoreLocation instead.
