### ISSUE TITLE
No longer seems to compile

### ISSUE THREAD

**Issue by DomT4** [victor/whereami#15]
[Build log](https://gist.githubusercontent.com/anonymous/c660b24c78d4d54efa40/raw/bbfcc661610f5b8cbde059b6e68680db95b1d777/01.xcodebuild).

Doesn't seem to build any more after the last couple of Xcode updates.

**Comment by victor** [comment]
Sorry, I had not seen the notification for this issue until now. Looks like a problem with the new downcasting syntax. I'll get that fixed soon.

**Comment by DomT4** [comment]
Thanks! Could you possibly cut a new tag? It'll make [packaging](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/whereami.rb) easier given the non-compile of the existing release against newer Xcodes.

**Comment by victor** [comment]
good point. Will do

**Comment by DomT4** [comment]
Any update on the tag? Someone else opened a new issue on the same thing: #17

**Comment by victor** [comment]
Well, the thing is the app depends on SwiftCLI, which hasn't been updated for Swift 1.2 or Swift 2 yet. I'm waiting a few days to see if (and how) they do update, there is currently a branch for Swift 2 on that project but I can't get it to work yet.

**Comment by victor** [comment]
Once I'm done updating to Swift 2, I'll cut the tag (currently HEAD is not building correctly, so no point in tagging it)
