### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by lhlpasser** [victor/whereami#16]
lihongyes-MacBook-Air:whereami lihongye$ git clone git@github.com:victor/whereami.git whereami
Cloning into 'whereami'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by victor** [comment]
Hi Kevin,

 if you don't have a github account, you can clone from `https://github.com/victor/whereami.git` instead of `git@github.com/victor/whereami`.
Or you can just use homebrew:

```
homebrew update && homebrew install whereami
```

**Comment by lhlpasser** [comment]
thanks !
I was manage to run you app !
do you consider to add some funny function to you app ? like showing you location in the map or something else....

**Comment by victor** [comment]
Not really. The Maps app already shows your location by itself, so there's no need for that.
I plan to add other features as time permits, though.
