### ISSUE TITLE
Unable to install with `brew` @ 0.9.5

### ISSUE THREAD

**Issue by cburmeister** [victor/whereami#18]
I'm getting the following error when trying to install via Homebrew:

```
$ brew install whereami 
==> Installing whereami from victor/homebrew-whereami
==> Downloading https://github.com/victor/whereami/archive/v1.0.tar.gz
==> xcodebuild install DSTROOT=/usr/local/Cellar/whereami/1.0 INSTALL_PATH=/bin
Last 15 lines from /Users/cburmeister/Library/Logs/Homebrew/whereami/01.xcodebuild:
2015-11-30 12:27:58 -0800

xcodebuild
install
DSTROOT=/usr/local/Cellar/whereami/1.0
INSTALL_PATH=/bin

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/victor/homebrew-whereami/issues
```

**Comment by victor** [comment]
Corey can you specify with which Xcode and which OS version are you trying to install it?
Looks like you don't have the full Xcode, but only the command line tools. Is that so?

**Comment by cburmeister** [comment]
@victor thanks for the swift reply! I'm on OSX 10.10.5 with the Xcode command line tools @ 7.1.0.0.1.1444952191. Is a full install of Xcode necessary for `whereami`?

**Comment by victor** [comment]
I'm not sure, I always install the full Xcode because I need it to work with.
Have you ever run the `xcode-select` command?
In theory it should be something like (even when using only the Command Line Tools install, it apparently still should be pointed at `/Applications/Xcode.app`):

```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```

**Comment by cburmeister** [comment]
I've used it in the past but not in my current environment. I installed Homebrew which subsequently installed the command line tools. Here is where the path is currently pointing:

```
$ xcode-select --print-path
/Library/Developer/CommandLineTools
```

**Comment by victor** [comment]
I've read that that specific path may be pointing to an empty install. So I'd ask you to see if there is something installed at `/Applications/Xcode.app/Contents/Developer` and if so, run the command supplied before (you can always reset it to the current path afterwards) and try again.
If not, I'm out of clues, perhaps a full install is needed to run **xcodebuild** after all
