### ISSUE TITLE
No update on network change.

### ISSUE THREAD

**Issue by apiarian** [victor/whereami#2]
When I move from home to the office, my location doesn't always get updated. I can be at the office for hours and my computer still seems to think that I am at home. If i run this little guy, http://cocoawithlove.com/2009/09/whereismymac-snow-leopard-corelocation.html , it shows the old location for a moment, and then updates to the new correct one. Any idea why this might be?

**Comment by victor** [comment]
Do you have Airport turned on, at your office? having it disconnected means CoreLocation gets no updates.
Also, my program is satisfied with the first result that the location manager returns, and then it ends; as opposed to where is my mac, which is listening continuously for location updates. It could very well be that my program is just getting a cached location, and by the time a new location is fixed, the program already ended. Try running it after whereismymac determines your location correctly and see if the location changes.

**Comment by apiarian** [comment]
There is wireless at the office and at home. And whereami does show the correct location once it has been retrieved by Where Is My Mac.app. I will fork and see if i can get  whereami to get a couple of updates before exiting, perhaps that will work. I should be able to let you know in a couple of days (testing by going back and forth between home and work).

**Comment by victor** [comment]
Yes, I modified it so that updates were continuous instead of stopping at the first one. But of course, I hardly can carry an iMac back and forth, so I need to test it on my MBP yet. Let me know what your results are, I am thinking that perhaps the first result should actually be **discarded** and wait for a second position fix.

**Comment by apiarian** [comment]
you are correct, when i modified it to take multiple readings, the first comes in very quickly and is definitely from the cache, and the second has the correct updated coordinates.
