### ISSUE TITLE
Homebrew!

### ISSUE THREAD

**Issue by laserlemon** [victor/whereami#6]
Would be great to be able to install this on Macs via:

``` bash
brew install whereami
```

**Comment by victor** [comment]
It's not the first time I get this suggestion. I will look into it.

thanks
victor

**Comment by reckter** [comment]
Hey, any news on that? I would love to use this, but I can't get it to compile on OSX 10.10,

thanks Hannes

**Comment by victor** [comment]
well, according to Homebrew's [Acceptable formulae](https://github.com/Homebrew/homebrew/wiki/Acceptable-Formulae) guide:

> We frown on authors submitting their own work unless it is very popular.

so, I might write the formula, but someone else would need to submit it, as I don't think this project is very popular yet.

Just out of curiosity, what is people using this tool for?

**Comment by wfalkwallace** [comment]
I've used it for git hooks (to make contribution graphs in projects like [wdjc](https://github.com/WHET-PLT/wdjc/blob/master/CONTRIBUTORS.geojson)) as well as tracking my work and connectivity geolocation (run as a daemon, this is mostly just for fun and to build a dataset to practice some dataviz).
I'm also working on an [ubersicht](https://github.com/felixhageloh/uebersicht) widget to display the info on the desktop.

---

I can try to submit it, if it's ready in your mind -- how do updates happen then? do I submit and you maintain? or am I charged with maintaining then?

**Comment by wfalkwallace** [comment]
@reckter, what issues are you seeing? mine compiled fine. See #7 for some advice as well.

**Comment by ladislas** [comment]
you don't need to be in the main homebrew repo to allow your users to install it this way.

you can just create a tap `https://github.com/victor/homebrew-whereami` with the formula.

We'll just need to `brew tap victor/whereami && brew install whereami` and voila! 

I can look into it if you want, just need to create the repo I can PR to.

**Comment by victor** [comment]
That's a very good point. I'll create a tap and upload it

**Comment by victor** [comment]
I've created a tap according to the docs but for some reason it isn't working.
If any of you can add it (`brew tap victor/whereami`) and confirm whether you get the same result as I do (`Tapped 0 formulae`) I'd appreciate it

**Comment by ladislas** [comment]
@victor you don't have to fork homebrew to do that.

just create an empty repository called `homebrew-whereami` and I'll PR to it. ;)

here is an example of what we'll do. https://github.com/WeAreLeka/homebrew-avr

**Comment by victor** [comment]
Thanks, I did as you suggested and it seems to work now. I already added the formula there – I had it working locally, just not within a tap yet.
I will do a commit later today to refine the test method, but it can already be used to install it
