### ISSUE TITLE
Can't build on 10.10

### ISSUE THREAD

**Issue by tjluoma** [victor/whereami#9]
I don't know much about building it, but when I open it and do 'Build' in Xcode, it says "Build Failed".

**Comment by victor** [comment]
Hi @tjluoma . Are you perhaps opening the `.xcodeproj` file? you should be opening the `.xcworkspace` file instead.
If that is not the problem, please copy Xcode's full output here so as to make a better diagnostic. Thanks

**Comment by tjluoma** [comment]
Yup. That's exactly what I was doing.

The build succeeds now. It left me with an executable at 

"$HOME/Library/Developer/Xcode/DerivedData/whereami-aigtcbxdtsgvkgbfeiavjwqgnlmv/Build/Products/Debug/whereami"

but whenever I try to run it, nothing happens, but I do get a new CoreLocationAgent crash log.

**Comment by victor** [comment]
Umm.. does it work if you run it directly from Xcode?
You should be getting an alert asking you for permission to give Location access to the program.

Anyway, you caught me in the middle of some modernization to the code. If you're not in a hurry, I'd ask you to wait for the next code push as the CoreLocation API has changed substantially – not to mention the code itself, which is so old that predates properties and other Obj-C niceties. If you are in a hurry indeed, then please try with the previous commit - though I haven't tested it on Yosemite so I don't know if it will work.

Oh and by the way, if you could share the crash log, that'd be appreciated, thanks

**Comment by tjluoma** [comment]
I'm not in a hurry at all, so I'll wait. I have a working binary of version 1.02 (I think).

(Be sure to add a `--version` flag in the new one :-)

**Comment by victor** [comment]
yes option support is why I added the GBCli pod in the first place. Will make sure to include the version option!

Thanks for your feedback
